IMPALA-9762: Fix GCC7 shift-count-overflow in tuple-row-compare.cc
This fixes a GCC 7 compilation error for this code in
TupleRowZOrderComparator's GetSharedIntRepresentation() and
GetSharedFloatRepresentation():

  return (static_cast<U>(val) <<
      std::max((sizeof(U) - sizeof(T)) * 8, (uint64_t)0)) ^ mask;

In this case, the std::max is running with uint64_t arguments. For
template instatiations with sizeof(T) > sizeof(U), this results
in integer overflow and a very large positive integer causing
the shift-count-overflow. These instantiations are not used by
Impala, but the compiler still needs to generate them.

This changes the logic to use signed integers for the std::max,
avoiding the shift-count-overflow.

Testing:
 - Build on GCC 4.9.2 and GCC 7
 - Core tests

Change-Id: I518e8bed1bb8d49d9cb76a33b07b665e15dfef87
Reviewed-on: http://gerrit.cloudera.org:8080/15962
Reviewed-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
Tested-by: Impala Public Jenkins <impala-public-jenkins@cloudera.com>
(cherry picked from commit f474b03dce35956d0762159eed16516b793903eb)
Reviewed-on: https://gerrit.sjc.cloudera.com/c/cdh/impala/+/85716
Reviewed-by: Joe McDonnell <joemcdonnell@cloudera.com>
CDH-Build: Jenkins User <jenkins@cloudera.com>
Quasar-L0: Jenkins User <jenkins@cloudera.com>
Tested-by: Jenkins User <jenkins@cloudera.com>